# use node base file
FROM python:3

# set working directory
WORKDIR /usr/src/app

# copy requirement.txt
# COPY requirement.txt ./

 

# set maintainer
LABEL maintainer "nischal.vijayadeva@gmail.com"




# run dependency installation
#RUN pip install -r requirement.txt


RUN pip install -U pip

COPY . .

EXPOSE 8000
 CMD ["python","chap1.py","runserver"]



