# use node base file
FROM nischalvijayadeva/tutorial_01:latest

# set working directory
#WORKDIR /usr/src/app

# copy requirement.txt
# COPY requirement.txt ./

# set maintainer
#LABEL maintainer "nischal.vijayadeva@gmail.com"

# run dependency installation
#RUN pip install -r requirement.txt





